name: chrome_storage_dart
description: >
  Element access to the chrome.storage API.
version: 0.0.1
author: <Brian Geppert> <briangeppert@briangeppert.com>
homepage: http://www.briangeppert.com
dependencies:
  polymer: any
  chrome: any
  polymer: ">=0.15.2 <0.16.0"
  unittest: ">=0.11.0+2 <0.12.0"
  web_components: ">=0.9.0 <0.11.0"
transformers:
- polymer
- chrome
